### ISSUE TITLE
Translate Introduction and Navigate section from english to german

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism-docs-de#1]
**Acceptance Criteria:**
* Follow the instructions in README.md to set up mkdocs locally on your system
* Translate the file: docs/user-guide/index.md to german
* Translate the file: docs/user-guide/navigate.md to german

**Notes:**
- Please do not rename the files 
- In case there is a link to a page that is not part of the user guide (e.g. a page from the developer guide) --> link to the english version

**Quality Standards:**
* We will not accept translation that have been made with google translate
* Test locally that formatting (e.g. *some text*) is working
* Test locally that links are working
* Test locally that icons are working --> do not translate something like: :material-folder:

**Comment by clairecharles** [comment]
Hey @graciousgrey can I take this on

**Comment by clairecharles** [comment]
Hey @graciousgrey just created a  pull request.
