### ISSUE TITLE
Translate Use Cases section from english to german

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism-docs-de#10]
**Acceptance Criteria:**

* Follow the instructions in README.md to set up mkdocs locally on your system
* Translate the file: docs/user-guide/use-cases/flickr.md to german
* Translate the file: docs/user-guide/use-cases/google.md to german

**Notes:**

* Please do not rename the files
* In case there is a link to a page that is not part of the user guide (e.g. a page from the developer guide) --> link to the english version

**Comment by sakshamsingh01** [comment]
I would love to work upon it!
