### ISSUE TITLE
Translate Index section from english to german

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism-docs-de#2]
**Acceptance Criteria:**

* Follow the instructions in README.md to set up mkdocs locally on your system
* Translate the file: docs/user-guide/library/files.md to german
* Translate the file: docs/user-guide/library/import.md to german
* Translate the file: docs/user-guide/library/import-vs-index.md to german
* Translate the file: docs/user-guide/library/indexing.md to german
* Translate the file: docs/user-guide/library/upload.md to german
* Translate the file: docs/user-guide/library/webdav.md to german

**Notes:**

* Please do not rename the files
* In case there is a link to a page that is not part of the user guide (e.g. a page from the developer guide) --> link to the english version

**Quality Standards:**
* We will not accept translation that have been made with google translate
* Test locally that formatting (e.g. *some text*) is working
* Test locally that links are working
* Test locally that icons are working --> do not translate something like: :material-folder:

**Comment by Anita-ihuman** [comment]
can i tackle this please?

**Comment by graciousgrey** [comment]
Sure :)
