### ISSUE TITLE
Translate Backup section from english to german

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism-docs-de#7]
**Acceptance Criteria:**

* Follow the instructions in README.md to set up mkdocs locally on your system
* Translate the file: docs/user-guide/backup/nextcloud.md to german
* Translate the file: docs/user-guide/backup/webdav.md to german

**Notes:**

* Please do not rename the files
* In case there is a link to a page that is not part of the user guide (e.g. a page from the developer guide) --> link to the english version

**Comment by m1ga** [comment]
would like to help you here!

**Comment by m1ga** [comment]
I wasn't assigned yet, but I made the PR already. Be careful with some of the other translations. They look like Google translate from quickly scanning them!

**Comment by graciousgrey** [comment]
@m1ga Thank you! I will have a look at the pull requests later today :) In case translations are bad the tickets remain open.
