### ISSUE TITLE
Translate Share section from english to german

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism-docs-de#8]
**Acceptance Criteria:**

* Follow the instructions in README.md to set up mkdocs locally on your system
* Translate the file: docs/user-guide/share/share.md to german

**Notes:**

* Please do not rename the files
* In case there is a link to a page that is not part of the user guide (e.g. a page from the developer guide) --> link to the english version

**Comment by zlaytan25** [comment]
Hey I'm from Germany and I would love to tackle this issue!
