### ISSUE TITLE
Translate Settings section from english to german

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism-docs-de#9]
**Acceptance Criteria:**

* Follow the instructions in README.md to set up mkdocs locally on your system
* Translate the file: docs/user-guide/settings/account.md to german
* Translate the file: docs/user-guide/settings/library.md to german
* Translate the file: docs/user-guide/settings/places.md to german
* Translate the file: docs/user-guide/settings/thumbnails.md to german
* Translate the file: docs/user-guide/settings/ui.md to german

**Notes:**

* Please do not rename the files
* In case there is a link to a page that is not part of the user guide (e.g. a page from the developer guide) --> link to the english version

**Quality Standards:**
* We will not accept translation that have been made with google translate
* Test locally that formatting (e.g. *some text*) is working
* Test locally that links are working
* Test locally that icons are working --> do not translate something like: :material-folder:

**Comment by vikassethi09** [comment]
i would like work on this issue

**Comment by bhavesh1129** [comment]
i would like to do this work

**Comment by x789** [comment]
The texts are quite technical, but I think I can handle that. ;-)
